#!/usr/bin/env node
/**
 * The agent definitions live in core/agents/ — they are pipeline source and belong next to the
 * code that invokes them. Claude Code reads subagents from .claude/agents/, so this copies them
 * across. One source of truth, one direction of copy.
 *
 * Run after editing any agent definition:  node core/tools/sync-agents.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { AGENTS, ROOT } from '../pipeline/lib/paths.mjs';

const dest = path.join(ROOT, '.claude', 'agents');
fs.mkdirSync(dest, { recursive: true });

const files = fs.readdirSync(AGENTS).filter((f) => f.endsWith('.md') && f !== 'ISOLATION.md');
if (!files.length) {
  console.error(`no agent definitions in ${AGENTS}`);
  process.exit(2);
}

for (const f of files) {
  const src = path.join(AGENTS, f);
  const body = fs.readFileSync(src, 'utf8');
  if (!body.startsWith('---')) {
    console.error(`✗ ${f}: missing YAML frontmatter — Claude Code will not load it as a subagent`);
    process.exitCode = 1;
    continue;
  }
  const name = /^name:\s*(\S+)/m.exec(body)?.[1];
  if (!name) {
    console.error(`✗ ${f}: frontmatter has no name:`);
    process.exitCode = 1;
    continue;
  }
  // The note goes after the frontmatter block: YAML frontmatter must start on line 1 or
  // Claude Code will not recognise the file as a subagent definition.
  const end = body.indexOf('\n---', 3);
  const note = `\n\n<!-- generated by core/tools/sync-agents.mjs from core/agents/${f} — edit the source, not this -->`;
  const out = end === -1 ? body : body.slice(0, end + 4) + note + body.slice(end + 4);

  const target = path.join(dest, `${name}.md`);
  fs.writeFileSync(target, out);
  console.log(`✓ ${f} → ${path.relative(ROOT, target)}`);
}
