#!/usr/bin/env node
/**
 * Skills live in core/skills/ — they are pipeline source, versioned with the code that relies on
 * them. Claude Code reads skills from .claude/skills/, so this copies them across.
 *
 * One source of truth, one direction of copy, same arrangement as tools/sync-agents.mjs.
 * The installed third-party skills in .claude/skills/ are left alone.
 */
import fs from 'node:fs';
import path from 'node:path';
import { CORE, ROOT } from '../pipeline/lib/paths.mjs';

const src = path.join(CORE, 'skills');
const dest = path.join(ROOT, '.claude', 'skills');

if (!fs.existsSync(src)) { console.error(`no skills in ${src}`); process.exit(2); }
fs.mkdirSync(dest, { recursive: true });

for (const name of fs.readdirSync(src)) {
  const from = path.join(src, name, 'SKILL.md');
  if (!fs.existsSync(from)) continue;

  const body = fs.readFileSync(from, 'utf8');
  if (!body.startsWith('---')) {
    console.error(`✗ ${name}: missing YAML frontmatter — Claude Code will not load it`);
    process.exitCode = 1;
    continue;
  }

  // The note goes after the frontmatter: it must start on line 1 to be recognised.
  const end = body.indexOf('\n---', 3);
  const note = `\n\n<!-- generated by core/tools/sync-skills.mjs from core/skills/${name}/ — edit the source -->`;
  const out = end === -1 ? body : body.slice(0, end + 4) + note + body.slice(end + 4);

  fs.mkdirSync(path.join(dest, name), { recursive: true });
  fs.writeFileSync(path.join(dest, name, 'SKILL.md'), out);
  console.log(`✓ ${name} → ${path.relative(ROOT, path.join(dest, name, 'SKILL.md'))}`);
}
